
[build]
 base = "."
 publish = "client"
[dev]
publish = "client"



[dev.https]
    certFile = "cert.pem" # path to the certificate file
    keyFile = "key.pem" # path to the private key file

[[redirects]]
from ="/api/fb-dev/*"
to="http://localhost:9000/:splat"
force = true
  status = 200






[functions]
  directory = "netlify/functions"