name: bdd
on:
  push:
    branches:
      - master
env:
  headless: true
  databaseURL: http://localhost:9000
  client_id: 117708549296-uij0mup1c3biok6ifaupa2951vtvf418.apps.googleusercontent.com
  webapikey: AIzaSyDb8Z27Ut0WJ-RH7Exi454Bpit9lbARJeA
  requestUri: https://turkmenistan-market.firebaseapp.com/__/auth/handler
  gh_client_id: 9cbffc6392ae35c84962
  host: https://localhost:8888
  redirectUrl: https://localhost:8888/.netlify/functions/auth-callback
  databaseHost: localhost
  dbPort: 9000
  dbSsh: false
  GITHUBPASS:  ${{secrets.GITHUBPASS}}
  GH_CLIENT_SECRET:  ${{secrets.GH_CLIENT_SECRET}}
  TOKEN:  ${{secrets.TOKEN}}
  REFRESHTOKEN:  ${{secrets.REFRESHTOKEN}}
  IDTOKEN:  ${{secrets.IDTOKEN}}
  NETLIFY_AUTH_TOKEN: ${{secrets.DEPLOY_NETL_TKN}}
  NETLIFY_SITE_ID: ${{secrets.NETLIFY_SITE_ID}}
  CRPKY: ${{secrets.CRPKY}}
  gh_action: 'true'
  ACTIONS_RUNTIME_TOKEN: ${{secrets.ACTIONS_RUNTIME_TOKEN}}
  BDD_TEST: 'TRUE'
jobs:
  bdd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cache node modules
        uses: actions/cache@v2
        env:
         cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS...
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install project dependencies
        run: 'npm install'
      - name: Install netlify
        run: 'npm install netlify-cli --save-dev'
      - name: Install firebase cli
        run: 'npm install -g firebase-tools'
      - name: Decript data
        run: 'npm run decryptData'
      - name: Run bdd test
        id: bddtest
        run: npm run bddCITest
      - name: deploy to netlify
        if: ${{steps.bddtest.outcome =='success'}}
        run: netlify deploy --prod